### ISSUE TITLE
Performance difference

### ISSUE THREAD

**Issue by DemonsHunter** [OpenNLPLab/AVSBench#10]
I reconduct experiments with 5 random seed based on your open-source code, But fail to hit the appearance as your paper reported.

Concrectly, in the paper:
![image](https://user-images.githubusercontent.com/44830115/198949395-a2566be8-a7eb-4071-880d-69f35dd2dcba.png)

While in my expremiment result:
![image](https://user-images.githubusercontent.com/44830115/198950201-ac646a7c-d5f1-414f-94b3-f525e26f29e2.png)

I wonder if I miss something or it is due to the version difference of a specific dependency package.

Thank you for your reply and time!

**Comment by jasongief** [comment]
Sorry for the late reply and thanks for these reproduced results.  As the results show, performances over multiple runs often fluctuate for segmentation tasks especially when you changed the seed. I think the averaged results are bearable.
