### ISSUE TITLE
Class category for multi source data

### ISSUE THREAD

**Issue by cyh-0** [OpenNLPLab/AVSBench#11]
Hi,

Thanks for sharing the dataset, I am wondering do we have category labels for the multi-source videos.

Cheers,
Yuanhong

**Comment by jasongief** [comment]
Hi Yuanhong,

Thanks for your attention. We have recently updated the category labels for the multi-source videos to keep consistent with the newly collected AVSBenchV2. We will make it available as soon as possible.
