### ISSUE TITLE
about FREEZE_VISUAL_EXTRACTOR

### ISSUE THREAD

**Issue by Divine0719** [OpenNLPLab/AVSBench#14]
Hello,
In AVSBench/avs_scripts/avss/config.py , it's set that "cfg.TRAIN.FREEZE_VISUAL_EXTRACTOR = True".
However, I can't find where this param is used.
Can you please tell me where you set the visual extractor's param freezed?

Many thanks!

**Comment by jasongief** [comment]
Hi, It seems that we do not use this param in the code except in this config.py file. The visual backbones (i.e., ResNet50 and PVT-v2) for exacting features are frozen in our model.
