### ISSUE TITLE
visual_backone frozen issue

### ISSUE THREAD

**Issue by Divine0719** [OpenNLPLab/AVSBench#15]
Hello,
I found that the visual backbone might not be frozen correctly when I added following to train.py
    for name, param in model.named_parameters():
        print(str(name)+':'+str(param.requires_grad))
here is the result
![微信截图_20230505103032](https://user-images.githubusercontent.com/77132276/236366369-05f9b725-ff02-4ac2-a4c2-08ea8e57811a.png)

I used the following code to correct the problem.
    for name, param in model.named_parameters():  
        if "encoder_backbone" in name:
            param.requires_grad = False

I was not too sure about this，and hope to hear from you~
Thx a lot!!!

**Comment by jasongief** [comment]
Hi, thanks for this issue. In our implementation, we directly load the pretrained parameters of visual backbones in the testing phase. The way you shown is correct and will be more precise. Have you got the corresponding result? Is there a big difference between the two ways?

Best,

**Comment by Divine0719** [comment]
Hi, result is will be little better, but not much. Freezing the visual backbone can help to enlarge batch_size and get faster convergence, which may save  lot of time and electric charge.

**Comment by lzeeorno** [comment]
hi, did you run train.py successfully? i meet some cuda problem when i run the train.py. Would you able to tell me your environment list to run this project? 
CUDA xx.x?
Python 3.x?
Pytorch 1.x.x?
My bug shows: 
model = torch.nn.DataParallel(model).cuda()
UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554800319/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
