### ISSUE TITLE
What is the difference among Single Sound Source Segmentation (S4), Multiple Sound Source Segmentation (MS3), and Audio-Visual Semantic Segmentation (AVSS)?

### ISSUE THREAD

**Issue by Ako-r** [OpenNLPLab/AVSBench#18]
Same as the title.

**Comment by jasongief** [comment]
Hi, thanks for your interest. 

S4, MS3, and AVSS are different settings of the AVS task that aims to segment the sounding object(s). S4 setting studies the simpler case of a single sound source (sounding object) in the video, whereas there are multiple sounding objects in the MS3 and AVSS settings. In S4 and MS4 settings, the sound source are segmented through binary map to denote the location corresponding to the sound, while AVSS needs to further judge the category of the sounding objects.

Please refer to our arxiv paper for more details about these settings and the proposed AVSBench dataset: [https://arxiv.org/abs/2301.13190](https://arxiv.org/abs/2301.13190)

**Comment by Ako-r** [comment]
Hi! Thanks for your reply. 


I also want to know how to obtain the following files.


cfg.DATA = edict()
cfg.DATA.ANNO_CSV = "../../avsbench_data/Single-source/s4_meta_data.csv"
cfg.DATA.DIR_IMG = "../../avsbench_data/Single-source/s4_data/visual_frames"
cfg.DATA.DIR_AUDIO_LOG_MEL = "../../avsbench_data/Single-source/s4_data/audio_log_mel"
cfg.DATA.DIR_MASK = "../../avsbench_data/Single-source/s4_data/gt_masks"


Looking forward to your feedback. Thanks again.
| |
m18321681162_1
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/27/2023 09:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [OpenNLPLab/AVSBench] What is the difference among Single Sound Source Segmentation (S4), Multiple Sound Source Segmentation (MS3), and Audio-Visual Semantic Segmentation (AVSS)? (Issue #18) |

Hi, thanks for your interest.

S4, MS3, and AVSS are different settings of the AVS task that aims to segment the sounding object(s). S4 setting studies the simpler case of a single sound source (sounding object) in the video, whereas there are multiple sounding objects in the MS3 and AVSS settings. In S4 and MS4 settings, the sound source are segmented through binary map to denote the location corresponding to the sound, while AVSS needs to further judge the category of the sounding objects.

Please refer to our arxiv paper for more details about these settings and the proposed AVSBench dataset: https://arxiv.org/abs/2301.13190
