### ISSUE TITLE
Raw video dataset

### ISSUE THREAD

**Issue by ryohachiuma** [OpenNLPLab/AVSBench#19]
Hi, thank you for providing an awesome dataset in public!
I have downloaded the AVSBench Semantics dataset, but is it possible to provide the raw video, instead of preprocessed frames/audio?

Thank you in advance.

**Comment by ryohachiuma** [comment]
I have found raw videos in Baidu Drive. Could you also upload that raw videos to OneDrive or DropBox?
I cannot create an account for Baidu...

**Comment by jasongief** [comment]
Hi, thanks for your interest, we have uploaded that dataset to OneDrive. You may send an email to [opennlplab@gmail.com.](mailto:opennlplab@gmail.com) for the dataset.

**Comment by ryohachiuma** [comment]
thank you for your quick response!
I will check OneDrive!
