### ISSUE TITLE
About data loading paths in config file

### ISSUE THREAD

**Issue by WaltPeter** [OpenNLPLab/AVSBench#20]
Hi, 
I noticed that the paths on config file does not match the file structure of AVSS dataset I received. 

Refer to line 37-42 in config.py
[https://github.com/OpenNLPLab/AVSBench/blob/9b3ef722c0fc86574c1c78dc9ce8819e01e774d4/avs_scripts/avss/config.py#L37](url) -L42

> cfg.DATA.META_CSV_PATH = "./avs_released/metadata.csv" #! notice: you need to change the path
> cfg.DATA.LABEL_IDX_PATH = "./avs_released/label2idx.json" #! notice: you need to change the path
> 
> cfg.DATA.DIR_BASE = "./avs_released" #! notice: you need to change the path
> cfg.DATA.DIR_MASK = "../../avsbench_data/v2_data/gt_masks" #! notice: you need to change the path
> cfg.DATA.DIR_COLOR_MASK = "../../avsbench_data/v2_data/gt_color_masks_rgb" #! notice: you need to change the path

However, in AVSS dataset, the structure is like 

> AVSBench-semantic
>      - v1m 
>           -- _19NVGk6Zt8_0
>                --- frames
>                     ---- 0.jpg
>                     ---- ...
>                --- labels_semantic
>                     ---- 0.png
>                     ---- ...
>                --- audio.wav
>      - v1s
>           -- ...
>      - v2
>           -- ...
>      - label2idx.json
>      - metadata.csv

Maybe there is a newer version of code? 
Thank you

**Comment by jasongief** [comment]
Hi, those file paths you mentioned are mainly used in the color_dataloader.py, you may modify them accordingly.
