### ISSUE TITLE
Is it right to use 'bg_idx = (masks.shape[1] - 1)' ?

### ISSUE THREAD

**Issue by liushenme** [OpenNLPLab/AVSBench#23]
Hi, 
   Your work is very interesting and I have a question about your code.
   Refer to line 42 in avss/loss.py, 
   ` bg_idx = (pred_masks.shape[1] - 1)`
    you define background idx as 'masks.shape[1] - 1', which is 70. But after I ran the code, I think the background idx should be 0, which is also defined in label2idx.json. Is there any problem?
    Thank you in advance.

**Comment by jasongief** [comment]
Sorry for the late reply. Thank you for pointing out this. I think you are right. There may be a misalignment when reorganizing the codes and dataset and I have updated the codes.
