### ISSUE TITLE
what does ‘start’ mean in the meta.csv?

### ISSUE THREAD

**Issue by lxa9867** [OpenNLPLab/AVSBench#4]
what does ‘starts’ mean in the meta.csv?

**Comment by jasongief** [comment]
Hi, thanks for your attention. The 'start' means the time we start to trim the raw video.

**Comment by lxa9867** [comment]
Thanks for your reply. I still have question about the miou metric. I consider it is a mistake since you cannot measure miou on your proposed dataset. Would you like to make some clarification about this part?

**Comment by lxa9867** [comment]
I consider you mean the f-iou (foreground iou)/ J-measure?
