### ISSUE TITLE
RuntimeError: shape '[-1, 5, 128]' is invalid for input of size 384

### ISSUE THREAD

**Issue by Klawens** [OpenNLPLab/AVSBench#6]
I got this error during training, seems like something wrong with audio_feature.
`Traceback (most recent call last):
  File "train.py", line 227, in <module>
    output, _, _ = model(imgs, audio_feature) # [bs*5, 1, 224, 224]
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/lsc/anaconda3/envs/avs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsc/AVSBench/avs_scripts/avs_s4/model/HRNet_AVSModel.py", line 249, in forward
    conv_feat_va, a_fea = self.tpavi_va(feature_map_list[i], audio_feature, stage=i)
  File "/home/lsc/AVSBench/avs_scripts/avs_s4/model/HRNet_AVSModel.py", line 210, in tpavi_va
    audio = audio.view(-1, 5, audio.shape[-1]) # [B, T, 128]
RuntimeError: shape '[-1, 5, 128]' is invalid for input of size 384`

The audio features are `torch.Size([3, 128]) torch.Size([2, 128])` , but should be `[B*5, 128]`. What causes the error?

**Comment by jasongief** [comment]
Hi, do you extract the audio features by yourself? 
1) For each video, the shape of the audio feature should be [1, 5, 128], where '5' represents the 5 seconds, and '128' is the feature dimension. Note there are several videos in the dataset that last less than 5 seconds, you should deal with this if you extract the audio feature by yourself. For example, you can repeat the last extracted visual image and the audio feature accordingly.
 2) According to the error log you showed, the dimension of your audio feature is not equal to 128, right?
You could send an email to zhoujxhfut@gmail.com for our processed video and audio data.

**Comment by Klawens** [comment]
> Hi, do you extract the audio features by yourself?
> 
> 1. For each video, the shape of the audio feature should be [1, 5, 128], where '5' represents the 5 seconds, and '128' is the feature dimension. Note there are several videos in the dataset that last less than 5 seconds, you should deal with this if you extract the audio feature by yourself. For example, you can repeat the last extracted visual image and the audio feature accordingly.
> 2. According to the error log you showed, the dimension of your audio feature is not equal to 128, right?
>    You could send an email to [zhoujxhfut@gmail.com](mailto:zhoujxhfut@gmail.com) for our processed video and audio data.

1. I understand. Thanks.
2. I'm using the processed dataset provided by you and still got the error. Same error occurred in MS3 and S4, pvt and ResNet.

**Comment by jasongief** [comment]
It seems that there is something wrong with the extracted audio features, could you please check the shape of the audio feature?

**Comment by GenjiB** [comment]
@Klawens  This issue is only happened when you use multiple GPUs. if you want to use multi-gpus for training, make sure (B*T, -1) operation in the model instead in train.py

**Comment by Klawens** [comment]
> @Klawens This issue is only happened when you use multiple GPUs. if you want to use multi-gpus for training, make sure (B*T, -1) operation in the model instead in train.py

Thanks!

**Comment by Devin-Pi** [comment]
> @Klawens This issue is only happened when you use multiple GPUs. if you want to use multi-gpus for training, make sure (B*T, -1) operation in the model instead in train.py

Hi, thanks for your reply! I want to make sure that the location of operation (B*T, -1) is behind the "audio_feature = audio_backbone(audio)" ? Looking forward to your reply!

**Comment by GenjiB** [comment]
@RendongPi  do reshape in pvt_avsmodel.py. comment out reshape in train.py

**Comment by Devin-Pi** [comment]
> @RendongPi do reshape in pvt_avsmodel.py. comment out reshape in train.py

Thanks for youre reply! I will try it.

**Comment by Devin-Pi** [comment]
> > @Klawens This issue is only happened when you use multiple GPUs. if you want to use multi-gpus for training, make sure (B*T, -1) operation in the model instead in train.py
> 
> Hi, thanks for your reply! I want to make sure that the location of operation (B*T, -1) is behind the "audio_feature = audio_backbone(audio)" ? Looking forward to your reply!

This issue can be solved by the DDP.

**Comment by jnjz** [comment]
You can try drop_last=True or,
make sure the first dimension of imgs and audio_feature = batch_size before passing to the model. (reshape the imgs in model.forward instead of train.py, and reshape the audio_feature in train.py instead of model.tpavi_va)
I didn't tried the first solution, because the second works for me
