### ISSUE TITLE
Pretrained Weights 

### ISSUE THREAD

**Issue by abhigoku10** [OpenNLPLab/AVSBench#9]
@jasongief @OpenNLPLab123  Hi thanks for sharing the code base , can you please share the pretrained weights so that I can check its inference and see the results 

Thanks in advance

**Comment by jasongief** [comment]
Hi, thanks for your attention. It is disappointing that I did not keep the original pre-trained weights. You may need to retrain the AVS model with the provided data.

**Comment by jasongief** [comment]
@abhigoku10 Hope all is well. We have released the pretrained AVSS weights which are available at [https://drive.google.com/drive/folders/1faSG_Hs2D2PkYeXLyRqlo-cjZ-DmggKB?usp=sharing](https://drive.google.com/drive/folders/1faSG_Hs2D2PkYeXLyRqlo-cjZ-DmggKB?usp=sharing).
